// Generated by scripts/optimize-photos.ts — do not edit by hand. Run `npm run photos`.
export const PHOTO_FILES = [
  {
    id: "156a0506",
    width: 5374,
    height: 8057,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a0765",
    width: 4469,
    height: 6395,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a0792",
    width: 5001,
    height: 7395,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a0842",
    width: 8061,
    height: 5377,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a0913",
    width: 7972,
    height: 5317,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a1282",
    width: 5279,
    height: 7914,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a1335",
    width: 4791,
    height: 7085,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a1403",
    width: 5294,
    height: 7937,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a1406",
    width: 5378,
    height: 8063,
    widths: [640, 1280, 1920],
  },
  {
    id: "156a1428",
    width: 5321,
    height: 7978,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9779",
    width: 3018,
    height: 4305,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9813",
    width: 3767,
    height: 5650,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9825",
    width: 3907,
    height: 5860,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9830",
    width: 3871,
    height: 5807,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9875",
    width: 3730,
    height: 5595,
    widths: [640, 1280, 1920],
  },
  {
    id: "i4a9917",
    width: 3905,
    height: 5858,
    widths: [640, 1280, 1920],
  },
] as const;
