/**
 * Turns full-resolution photos into web-ready images.
 *
 *   npm run photos                       # design/My_Favorites -> public/photos
 *   npm run photos -- path/to/folder     # another source folder
 *
 * For each JPEG/PNG: auto-rotates, resizes to 640/1280/1920px wide (never
 * upscales), encodes WebP, and STRIPS ALL METADATA (camera data, GPS location).
 * Writes src/content/photos.generated.ts with each photo's id and dimensions.
 * Originals stay out of git (see .gitignore); only the web versions are committed.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const WIDTHS = [640, 1280, 1920] as const;
const QUALITY = 78;
const source = path.resolve(process.argv[2] ?? "design/My_Favorites");
const outDir = path.resolve("public/photos");
const manifestPath = path.resolve("src/content/photos.generated.ts");

/** "_I4A9779.jpg" -> "i4a9779" */
function photoId(file: string): string {
  return path
    .parse(file)
    .name.toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function main() {
  const files = readdirSync(source)
    .filter((f) => /\.(jpe?g|png)$/i.test(f))
    .sort();
  if (files.length === 0) throw new Error(`No photos found in ${source}`);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const entries: { id: string; width: number; height: number; widths: number[] }[] = [];
  for (const file of files) {
    const id = photoId(file);
    // .rotate() applies EXIF orientation; output has no metadata unless requested.
    const base = sharp(path.join(source, file), { failOn: "none" }).rotate();
    // Displayed dimensions: EXIF orientations 5–8 swap width and height.
    const meta = await sharp(path.join(source, file)).metadata();
    const swapped = (meta.orientation ?? 1) >= 5;
    const width = (swapped ? meta.height : meta.width) ?? 0;
    const height = (swapped ? meta.width : meta.height) ?? 0;
    const widths: number[] = WIDTHS.filter((w) => w <= width);
    if (widths.length === 0) widths.push(width);
    for (const w of widths) {
      await base
        .clone()
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: QUALITY, effort: 5 })
        .toFile(path.join(outDir, `${id}-${w}.webp`));
    }
    entries.push({ id, width, height, widths });
    console.log(`✓ ${file} -> ${id} (${width}×${height}, ${widths.join("/")}px)`);
  }

  writeFileSync(
    manifestPath,
    `// Generated by scripts/optimize-photos.ts — do not edit by hand. Run \`npm run photos\`.\n` +
      `export const PHOTO_FILES = ${JSON.stringify(entries, null, 2)} as const;\n`,
  );
  console.log(`\n${entries.length} photos → public/photos; manifest → src/content/photos.generated.ts`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
