-- =====================================================================
-- Invitations and invitation_guests
-- =====================================================================
-- An invitation is an issued invitation (one QR code, one fallback code).
-- It is separate from a household: an invitation may hold guests from any
-- household, and a household may receive more than one invitation.
--
-- Credentials:
--   token      24 chars of base64url = 144 bits from pgcrypto's CSPRNG.
--              Used in /i/{token}. Never derived from an internal ID.
--   rsvp_code  8 chars from a 31-char unambiguous alphabet (no 0/O/1/I/L),
--              about 8.5e11 combinations. Typed on /rsvp; lookups are throttled.
-- Both are always generated by the database; client-supplied values are
-- ignored on insert and rejected on update. Once locked, they are immutable.

-- ---------------------------------------------------------------------
-- Credential generators (private, not exposed through the Data API)
-- ---------------------------------------------------------------------
create function private.new_invitation_token()
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_token text;
begin
  loop
    -- 18 bytes -> exactly 24 base64 characters, no padding.
    v_token := translate(encode(extensions.gen_random_bytes(18), 'base64'), '+/', '-_');
    exit when not exists (select 1 from public.invitations where token = v_token);
  end loop;
  return v_token;
end;
$$;

create function private.new_rsvp_code()
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  c_alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; -- 31 characters
  v_code text;
  v_bytes bytea;
  v_byte integer;
  v_i integer;
begin
  loop
    v_code := '';
    v_bytes := extensions.gen_random_bytes(32);
    v_i := 0;
    while length(v_code) < 8 loop
      if v_i >= 32 then
        v_bytes := extensions.gen_random_bytes(32);
        v_i := 0;
      end if;
      v_byte := get_byte(v_bytes, v_i);
      v_i := v_i + 1;
      -- Rejection sampling (248 = 8 * 31) avoids modulo bias.
      if v_byte < 248 then
        v_code := v_code || substr(c_alphabet, (v_byte % 31) + 1, 1);
      end if;
    end loop;
    exit when not exists (select 1 from public.invitations where rsvp_code = v_code);
  end loop;
  return v_code;
end;
$$;

-- ---------------------------------------------------------------------
-- invitations
-- ---------------------------------------------------------------------
create table public.invitations (
  id uuid primary key default gen_random_uuid(),
  household_id uuid
    constraint invitations_household_id_fkey references public.households (id) on delete set null,
  -- Admin-facing label, e.g. "Smith Household".
  label text check (label is null or length(label) <= 200),
  -- Placeholder defaults satisfy NOT NULL; the trigger below always replaces them.
  token text not null default '' constraint invitations_token_key unique,
  rsvp_code text not null default '' constraint invitations_rsvp_code_key unique,
  status public.invitation_status not null default 'draft',
  generated_at timestamptz not null default now(),
  locked_at timestamptz,
  print_status public.print_status not null default 'not_printed',
  proof_printed_at timestamptz,
  printed_at timestamptz,
  qr_validation_status public.qr_validation_status not null default 'not_validated',
  validated_at timestamptz,
  -- The exact URL that was validated. If APP_BASE_URL later changes, the app
  -- treats the validation as stale.
  validated_url text,
  validation_details jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invitations_token_format check (token ~ '^[A-Za-z0-9_-]{24}$'),
  constraint invitations_rsvp_code_format check (rsvp_code ~ '^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{8}$')
);

create index invitations_household_id_idx on public.invitations (household_id);

create function private.invitations_before_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rotating boolean := coalesce(current_setting('app.rotate_invitation_credentials', true), '') = 'on';
begin
  if tg_op = 'INSERT' then
    new.token := private.new_invitation_token();
    new.rsvp_code := private.new_rsvp_code();
    new.generated_at := now();
    new.locked_at := case when new.status = 'locked' then now() end;
    new.print_status := 'not_printed';
    new.proof_printed_at := null;
    new.printed_at := null;
    new.qr_validation_status := 'not_validated';
    new.validated_at := null;
    new.validated_url := null;
    new.validation_details := null;
    return new;
  end if;

  -- Locking is one-way.
  if old.locked_at is not null then
    new.locked_at := old.locked_at;
    if new.status = 'draft' then
      raise exception 'Invitation is locked and cannot return to draft'
        using errcode = 'check_violation';
    end if;
  elsif new.status = 'locked' then
    new.locked_at := now();
  else
    new.locked_at := null;
  end if;

  -- Credentials change only through public.regenerate_invitation_token().
  if new.token is distinct from old.token or new.rsvp_code is distinct from old.rsvp_code then
    if not v_rotating then
      raise exception 'Invitation credentials can only be changed by regenerate_invitation_token()'
        using errcode = 'insufficient_privilege';
    end if;
    if old.locked_at is not null then
      raise exception 'Invitation is locked; its token is immutable'
        using errcode = 'check_violation';
    end if;
    new.generated_at := now();
    new.qr_validation_status := 'not_validated';
    new.validated_at := null;
    new.validated_url := null;
    new.validation_details := null;
    -- A proof printed with the old token no longer scans to this invitation.
    if new.print_status = 'proof_printed' then
      new.print_status := 'not_printed';
      new.proof_printed_at := null;
    end if;
  else
    new.generated_at := old.generated_at;
  end if;

  -- Printing rules.
  if old.print_status = 'printed' and new.print_status <> 'printed' then
    raise exception 'A printed invitation cannot be marked unprinted'
      using errcode = 'check_violation';
  end if;
  if new.print_status = 'printed' and old.print_status <> 'printed' then
    if new.locked_at is null then
      raise exception 'Lock the invitation before marking it printed'
        using errcode = 'check_violation';
    end if;
    if new.qr_validation_status <> 'passed' then
      raise exception 'Validate the QR code before marking the invitation printed'
        using errcode = 'check_violation';
    end if;
    new.printed_at := now();
  end if;
  if new.print_status = 'proof_printed' and old.print_status <> 'proof_printed' then
    new.proof_printed_at := now();
  end if;

  return new;
end;
$$;

create trigger invitations_before_write
  before insert or update on public.invitations
  for each row execute function private.invitations_before_write();

create trigger invitations_set_updated_at
  before update on public.invitations
  for each row execute function private.set_updated_at();

alter table public.invitations enable row level security;

create policy "Admins manage invitations"
  on public.invitations for all
  to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

revoke all on public.invitations from anon;

-- ---------------------------------------------------------------------
-- invitation_guests: which guests an invitation covers.
-- ---------------------------------------------------------------------
create table public.invitation_guests (
  invitation_id uuid not null
    constraint invitation_guests_invitation_id_fkey references public.invitations (id) on delete cascade,
  guest_id uuid not null
    constraint invitation_guests_guest_id_fkey references public.guests (id) on delete cascade,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (invitation_id, guest_id)
);

create index invitation_guests_guest_id_idx on public.invitation_guests (guest_id);

-- Changing who an invitation covers invalidates any prior QR validation,
-- because validation proves the token resolves to the expected guests.
create function private.invitation_guests_reset_validation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ids uuid[];
begin
  if tg_op = 'INSERT' then
    v_ids := array[new.invitation_id];
  elsif tg_op = 'DELETE' then
    v_ids := array[old.invitation_id];
  else
    v_ids := array[old.invitation_id, new.invitation_id];
  end if;

  update public.invitations
     set qr_validation_status = 'not_validated',
         validated_at = null,
         validated_url = null,
         validation_details = null
   where id = any (v_ids)
     and qr_validation_status <> 'not_validated';

  return null;
end;
$$;

create trigger invitation_guests_reset_validation
  after insert or update or delete on public.invitation_guests
  for each row execute function private.invitation_guests_reset_validation();

alter table public.invitation_guests enable row level security;

create policy "Admins manage invitation_guests"
  on public.invitation_guests for all
  to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

revoke all on public.invitation_guests from anon;

-- ---------------------------------------------------------------------
-- Admin RPC: rotate an unlocked invitation's token and RSVP code.
-- ---------------------------------------------------------------------
create function public.regenerate_invitation_token(p_invitation_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'not_authorized' using errcode = 'insufficient_privilege';
  end if;

  perform set_config('app.rotate_invitation_credentials', 'on', true);

  update public.invitations
     set token = private.new_invitation_token(),
         rsvp_code = private.new_rsvp_code()
   where id = p_invitation_id;

  if not found then
    raise exception 'invitation_not_found' using errcode = 'no_data_found';
  end if;

  perform set_config('app.rotate_invitation_credentials', 'off', true);
end;
$$;

revoke execute on function public.regenerate_invitation_token(uuid) from public, anon;
grant execute on function public.regenerate_invitation_token(uuid) to authenticated, service_role;
